## Makefile.inc for os in /home/projets/os/img
## 
## Made by Faltad
## Login   <faltad@gmail.com>
## 
## Started on  Tue Jun 29 00:22:40 2010 Faltad
## Last update Tue Jun 29 00:23:57 2010 Faltad
##


KERNEL		=	kernel.bin
GRUB_IMG	=	floppy.img

